'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DS_EventHook.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2|Gaping Dragon
        '''3|Bell Gargoyles
        '''4|Priscilla
        '''5|Sif
        '''6|Pinwheel
        '''7|Nito
        '''9|Chaos Witch Quelaag
        '''10|Bed of Chaos
        '''11|Iron Golem
        '''12|Ornstein &amp; Smough
        '''13|4 Kings
        '''14|Seath
        '''15|Gwyn
        '''1000|Solaire at first position
        '''1004|Solaire is hostile
        '''1005|Solaire is dead
        '''11010100|Undead Burg ladder kicked
        '''11010901|Taurus Demon
        '''11010902|Capra Demon
        '''11200900|Moonlight Butterfly
        '''11210000|Sanctuary Guardian
        '''11210001|Artorias
        '''11210002|Manus
        '''11210004|Kalameet
        '''11410410|Demon Firesage
        '''11410900|Ceaseless Discharge
        '''1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NamedIDs() As String
            Get
                Return ResourceManager.GetString("NamedIDs", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
